-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.character_visual_generations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  character_id uuid NOT NULL,
  prompt text NOT NULL,
  visual_style text,
  generation_type text NOT NULL,
  image_url text,
  status text DEFAULT 'pending'::text,
  job_id text,
  error_message text,
  is_selected boolean DEFAULT false,
  user_rating integer,
  model_used text,
  generation_params jsonb,
  CONSTRAINT character_visual_generations_pkey PRIMARY KEY (id),
  CONSTRAINT character_visual_generations_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.characters(id)
);
CREATE TABLE public.characters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  series_id uuid NOT NULL,
  name text NOT NULL,
  role text NOT NULL,
  description text NOT NULL,
  character_arc text,
  visual_prompt text NOT NULL,
  visual_keywords ARRAY,
  age_range text,
  physical_traits jsonb,
  distinctive_features ARRAY,
  clothing_style text,
  poster_url text,
  poster_status text DEFAULT 'pending'::text,
  poster_job_id text,
  poster_prompt text,
  reference_images jsonb,
  color_palette ARRAY,
  first_appearance_episode_id uuid,
  main_episodes ARRAY,
  relationships jsonb,
  current_status text DEFAULT 'active'::text,
  status_as_of_episode_id uuid,
  importance_level integer DEFAULT 5,
  is_recurring boolean DEFAULT true,
  tags ARRAY,
  CONSTRAINT characters_pkey PRIMARY KEY (id),
  CONSTRAINT characters_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id),
  CONSTRAINT characters_first_appearance_episode_id_fkey FOREIGN KEY (first_appearance_episode_id) REFERENCES public.episodes(id),
  CONSTRAINT characters_status_as_of_episode_id_fkey FOREIGN KEY (status_as_of_episode_id) REFERENCES public.episodes(id)
);
CREATE TABLE public.episodes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  series_id uuid NOT NULL,
  season_number integer NOT NULL,
  episode_number integer NOT NULL,
  title text NOT NULL,
  synopsis text NOT NULL,
  full_script text,
  story_beats ARRAY,
  featured_characters jsonb,
  target_duration integer DEFAULT 180,
  actual_duration integer,
  previous_episode_recap text,
  cliffhanger text,
  next_episode_tease text,
  status text DEFAULT 'draft'::text,
  video_url text,
  video_status text,
  video_job_id text,
  thumbnail_url text,
  is_finale boolean DEFAULT false,
  is_premiere boolean DEFAULT false,
  CONSTRAINT episodes_pkey PRIMARY KEY (id),
  CONSTRAINT episodes_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id)
);
CREATE TABLE public.generations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  story_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['story'::text, 'image'::text, 'audio'::text, 'video'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text])),
  start_time timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  end_time timestamp with time zone,
  duration_ms integer,
  provider text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT generations_pkey PRIMARY KEY (id),
  CONSTRAINT generations_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text CHECK (char_length(full_name) >= 3),
  avatar_url text,
  updated_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.segments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  story_id uuid NOT NULL,
  segment_index integer NOT NULL,
  duration_seconds integer NOT NULL DEFAULT 5,
  text text NOT NULL,
  visual_prompt text NOT NULL,
  image_url text,
  audio_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  episode_id uuid,
  segment_type text DEFAULT 'main'::text,
  character_focus text,
  CONSTRAINT segments_pkey PRIMARY KEY (id),
  CONSTRAINT segments_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.stories(id),
  CONSTRAINT segments_episode_id_fkey FOREIGN KEY (episode_id) REFERENCES public.episodes(id)
);
CREATE TABLE public.series (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  tagline text,
  base_concept text NOT NULL,
  full_lore text NOT NULL,
  genre ARRAY,
  themes ARRAY,
  setting text,
  planned_seasons integer DEFAULT 1,
  current_season integer DEFAULT 1,
  episodes_per_season integer DEFAULT 6,
  narrative_style text,
  target_duration_per_episode integer DEFAULT 180,
  visual_style text,
  script_style text,
  main_characters jsonb,
  status text DEFAULT 'draft'::text,
  user_id uuid,
  is_public boolean DEFAULT false,
  tags ARRAY,
  series_poster_url text,
  series_poster_status text DEFAULT 'pending'::text,
  series_poster_job_id text,
  series_poster_prompt text,
  series_visual_keywords ARRAY,
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.series_arcs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  series_id uuid NOT NULL,
  arc_name text NOT NULL,
  arc_description text,
  start_season integer NOT NULL,
  start_episode integer NOT NULL,
  end_season integer,
  end_episode integer,
  main_conflict text,
  resolution text,
  key_revelations ARRAY,
  CONSTRAINT series_arcs_pkey PRIMARY KEY (id),
  CONSTRAINT series_arcs_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id)
);
CREATE TABLE public.series_poster_generations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  series_id uuid NOT NULL,
  prompt text NOT NULL,
  visual_style text,
  image_url text,
  status text DEFAULT 'pending'::text,
  job_id text,
  error_message text,
  is_selected boolean DEFAULT false,
  user_rating integer,
  model_used text,
  generation_params jsonb,
  CONSTRAINT series_poster_generations_pkey PRIMARY KEY (id),
  CONSTRAINT series_poster_generations_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id)
);
CREATE TABLE public.stories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  base_idea text NOT NULL,
  story_title text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  visual_style text,
  script_tone text,
  video_url text,
  video_status text DEFAULT 'idle'::text,
  video_job_id text,
  profile_id uuid,
  CONSTRAINT stories_pkey PRIMARY KEY (id),
  CONSTRAINT stories_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);